global using System.Security.Cryptography;
global using Microsoft.Extensions.DependencyInjection;
global using SpeedBoot.Configuration;
global using SpeedBoot.Core;
global using Microsoft.Extensions.Configuration;
global using SpeedBoot.System;
global using SpeedBoot.Extensions.IdGenerator.Sequential.Options;
global using SpeedBoot.Extensions.IdGenerator.Abstracts;
global using SpeedBoot.Extensions.IdGenerator.Sequential;
